default: &default
  host: 192.168.59.103
  port: 5432
  adapter: postgresql
  username: postgres
  password: teetime
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: teetime_development

test:
  <<: *default
  database: teetime_test

production:
  <<: *default
  database: teetime_production
  password: <%= ENV['TEETIME_DATABASE_PASSWORD'] %>
